name: ${serviceVariable.name}
image: ${artifact.metadata.image}
stageName: ${serviceVariable.stageName}
primaryName: ${serviceVariable.primaryName}
endpoint: color-bg
stageEndpoint: color-bg-stage
primaryEndpoint: color-bg-primary

replicas: 2
namespace: ${infra.kubernetes.namespace}



include: false
