apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{.Values.name}}
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
#
# Main ingress for the backend that will split between stage and primary during deployment
#
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{.Values.name}}
spec:
  hosts:
  - "*"
  gateways:
  - {{.Values.name}}
  http:
  - match:
    - uri:
        exact: /{{.Values.endpoint}}
    rewrite:
      uri: /color/index.html
    route:
    - destination:
        host: {{.Values.primaryName}}
      weight: 100
    - destination:
        host: {{.Values.stageName}}
      weight: 0
---
#
# Dedicated ingress for stage
#
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{.Values.stageName}}
spec:
  hosts:
  - "*"
  gateways:
  - {{.Values.name}}
  http:
  - match:
    - uri:
        exact: /{{.Values.stageEndpoint}}
    rewrite:
      uri: /color/index.html
    route:
    - destination:
        host: {{.Values.stageName}}
---
#
# Dedicated ingress for primary
#
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{.Values.primaryName}}
spec:
  hosts:
  - "*"
  gateways:
  - {{.Values.name}}
  http:
  - match:
    - uri:
        exact: /{{.Values.primaryEndpoint}}
    rewrite:
      uri: /color/index.html
    route:
    - destination:
        host: {{.Values.primaryName}}
